#/bin/bash
  
#PBS -N em_dist_solve
#PBS -q emconnectome
#PBS -l nodes=2:ppn=1
#PBS -l walltime=0:02:00
#PBS -n
#PBS -j oe
#PBS -o /allen/programs/celltypes/workgroups/em-connectomics/danielk/EM_aligner_python/EMaligner/distributed
#PBS -m a
#PBS -M danielk@alleninstitute.org

module load mpi/mpich-x86_64

simf=/allen/programs/celltypes/workgroups/em-connectomics/danielk/EM_aligner_python/EMaligner/distributed/bin/petsc_solver.simf
input=/allen/programs/celltypes/workgroups/em-connectomics/danielk/EM_aligner_python/solution_input.h5
output=/allen/programs/celltypes/workgroups/em-connectomics/danielk/EM_aligner_python/tmp.h5

cat $PBS_NODEFILE > tmphosts

mpiexec -np $PBS_NUM_NODES -f tmphosts singularity run --bind /allen:/allen $simf -input $input -output $output -ksp_type preonly -pc_type lu -log_view
